; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Oct 22 2020 11:54:53 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATABRR19SAH0IC:
	dc.w DATABRR19SAH0IC_0-DATABRR19SAH0IC, DATABRR19SAH0IC_1-DATABRR19SAH0IC
	dc.w DATABRR19SAH0IC_2-DATABRR19SAH0IC, DATABRR19SAH0IC_3-DATABRR19SAH0IC
	dc.w DATABRR19SAH0IC_4-DATABRR19SAH0IC, DATABRR19SAH0IC_5-DATABRR19SAH0IC
	dc.w DATABRR19SAH0IC_6-DATABRR19SAH0IC, DATABRR19SAH0IC_7-DATABRR19SAH0IC
DATABRR19SAH0IC_0: dc.b $4
	dc.b $EC, $B, $9, $43, $F8
	dc.b $F4, $0, $9, $4F, $10
	dc.b $C, $C, $1, $50, $EC
	dc.b $C, $0, $1, $54, $C
DATABRR19SAH0IC_1: dc.b $4
	dc.b $C, $C, $1, $50, $EC
	dc.b $C, $0, $1, $54, $C
	dc.b $F0, $D, $80, $10, $EE
	dc.b $EC, $B, $9, $43, $F8
DATABRR19SAH0IC_2: dc.b $4
	dc.b $EC, $B, $9, $55, $F8
	dc.b $F4, $0, $9, $61, $10
	dc.b $C, $C, $9, $62, $F8
	dc.b $C, $0, $9, $66, $F0
DATABRR19SAH0IC_3: dc.b $4
	dc.b $EC, $B, $9, $43, $F8
	dc.b $F4, $0, $9, $4F, $10
	dc.b $C, $C, $1, $50, $EC
	dc.b $C, $0, $1, $54, $C
DATABRR19SAH0IC_4: dc.b $4
	dc.b $EC, $B, $1, $43, $F4
	dc.b $F4, $0, $1, $4F, $EC
	dc.b $C, $C, $9, $50, $F8
	dc.b $C, $0, $9, $54, $F0
DATABRR19SAH0IC_5: dc.b $3
	dc.b $EC, $6, $0, $3C, $F0
	dc.b $EC, $6, $8, $3C, $0
	dc.b $4, $D, $0, $42, $F0
DATABRR19SAH0IC_6: dc.b $7
	dc.b $B2, $C, $0, $4A, $F8
	dc.b $BA, $F, $0, $4E, $F0
	dc.b $BA, $5, $0, $5E, $10
	dc.b $CA, $2, $0, $62, $10
	dc.b $DA, $C, $0, $65, $F0
	dc.b $E2, $8, $0, $69, $F8
	dc.b $EA, $5, $0, $6C, $F8
DATABRR19SAH0IC_7: dc.b $18
	dc.b $80, $F, $0, $70, $F8
	dc.b $90, $B, $0, $80, $E0
	dc.b $90, $B, $0, $8C, $18
	dc.b $98, $B, $0, $98, $30
	dc.b $A0, $F, $0, $A4, $58
	dc.b $88, $0, $0, $B4, $F0
	dc.b $80, $5, $0, $B5, $18
	dc.b $A0, $F, $0, $B9, $F8
	dc.b $B0, $B, $0, $C9, $E0
	dc.b $B8, $F, $0, $D5, $38
	dc.b $A8, $5, $0, $E5, $48
	dc.b $C0, $2, $0, $E9, $58
	dc.b $C0, $F, $0, $EC, $F8
	dc.b $B8, $F, $0, $FC, $18
	dc.b $B0, $8, $1, $C, $18
	dc.b $D8, $D, $1, $F, $30
	dc.b $D8, $8, $1, $17, $18
	dc.b $D8, $F, $1, $1A, $D8
	dc.b $E0, $D, $1, $2A, $F8
	dc.b $E0, $0, $1, $32, $28
	dc.b $D0, $4, $1, $33, $E0
	dc.b $E8, $5, $1, $35, $C8
	dc.b $F8, $C, $1, $39, $C8
	dc.b $F0, $6, $1, $3D, $F8
	even