; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Oct 22 2020 09:24:26 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAX5N9B80T01Q:
	dc.w $0, DATAX5N9B80T01Q_1-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_2-DATAX5N9B80T01Q, DATAX5N9B80T01Q_3-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_4-DATAX5N9B80T01Q, DATAX5N9B80T01Q_5-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_6-DATAX5N9B80T01Q, DATAX5N9B80T01Q_7-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_8-DATAX5N9B80T01Q, DATAX5N9B80T01Q_9-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_A-DATAX5N9B80T01Q, DATAX5N9B80T01Q_B-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_C-DATAX5N9B80T01Q, DATAX5N9B80T01Q_D-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_E-DATAX5N9B80T01Q, DATAX5N9B80T01Q_F-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_10-DATAX5N9B80T01Q, DATAX5N9B80T01Q_11-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_12-DATAX5N9B80T01Q, DATAX5N9B80T01Q_13-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_14-DATAX5N9B80T01Q, DATAX5N9B80T01Q_15-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_16-DATAX5N9B80T01Q, DATAX5N9B80T01Q_17-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_18-DATAX5N9B80T01Q, DATAX5N9B80T01Q_19-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_1A-DATAX5N9B80T01Q, DATAX5N9B80T01Q_1B-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_1C-DATAX5N9B80T01Q, DATAX5N9B80T01Q_1D-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_1E-DATAX5N9B80T01Q, DATAX5N9B80T01Q_1F-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_20-DATAX5N9B80T01Q, DATAX5N9B80T01Q_21-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_22-DATAX5N9B80T01Q, DATAX5N9B80T01Q_23-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_24-DATAX5N9B80T01Q, DATAX5N9B80T01Q_25-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_26-DATAX5N9B80T01Q, DATAX5N9B80T01Q_27-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_28-DATAX5N9B80T01Q, DATAX5N9B80T01Q_29-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_2A-DATAX5N9B80T01Q, DATAX5N9B80T01Q_2B-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_2C-DATAX5N9B80T01Q, DATAX5N9B80T01Q_2D-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_2E-DATAX5N9B80T01Q, DATAX5N9B80T01Q_2F-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_30-DATAX5N9B80T01Q, DATAX5N9B80T01Q_31-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_32-DATAX5N9B80T01Q, DATAX5N9B80T01Q_33-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_34-DATAX5N9B80T01Q, DATAX5N9B80T01Q_35-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_36-DATAX5N9B80T01Q, DATAX5N9B80T01Q_37-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_38-DATAX5N9B80T01Q, DATAX5N9B80T01Q_39-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_3A-DATAX5N9B80T01Q, DATAX5N9B80T01Q_3B-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_3C-DATAX5N9B80T01Q, DATAX5N9B80T01Q_3D-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_3E-DATAX5N9B80T01Q, DATAX5N9B80T01Q_3F-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_40-DATAX5N9B80T01Q, DATAX5N9B80T01Q_41-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_42-DATAX5N9B80T01Q, $0
	dc.w $0, DATAX5N9B80T01Q_45-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_46-DATAX5N9B80T01Q, DATAX5N9B80T01Q_47-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_48-DATAX5N9B80T01Q, DATAX5N9B80T01Q_49-DATAX5N9B80T01Q
	dc.w $0, DATAX5N9B80T01Q_4B-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_4C-DATAX5N9B80T01Q, DATAX5N9B80T01Q_4D-DATAX5N9B80T01Q
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAX5N9B80T01Q_53-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_54-DATAX5N9B80T01Q, DATAX5N9B80T01Q_55-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_56-DATAX5N9B80T01Q, DATAX5N9B80T01Q_57-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_58-DATAX5N9B80T01Q, DATAX5N9B80T01Q_59-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_5A-DATAX5N9B80T01Q, DATAX5N9B80T01Q_5B-DATAX5N9B80T01Q
	dc.w DATAX5N9B80T01Q_5C-DATAX5N9B80T01Q, DATAX5N9B80T01Q_5D-DATAX5N9B80T01Q
DATAX5N9B80T01Q_1: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAX5N9B80T01Q_2: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAX5N9B80T01Q_3: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAX5N9B80T01Q_4: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAX5N9B80T01Q_5: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAX5N9B80T01Q_6: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAX5N9B80T01Q_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAX5N9B80T01Q_8: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAX5N9B80T01Q_9: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAX5N9B80T01Q_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAX5N9B80T01Q_B: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAX5N9B80T01Q_C: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAX5N9B80T01Q_D: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAX5N9B80T01Q_E: dc.b $5
	dc.b $FC, $C, $0, $0, $E8
	dc.b $EC, $9, $0, $4, $F0
	dc.b $4, $8, $0, $A, $F8
	dc.b $C, $8, $0, $D, $0
	dc.b $FC, $0, $0, $10, $8
DATAX5N9B80T01Q_F: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAX5N9B80T01Q_10: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAX5N9B80T01Q_11: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $8, $0, $9, $F4
	dc.b $C, $8, $0, $C, $FC
	dc.b $FC, $0, $0, $F, $4
DATAX5N9B80T01Q_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAX5N9B80T01Q_13: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAX5N9B80T01Q_14: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAX5N9B80T01Q_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAX5N9B80T01Q_16: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAX5N9B80T01Q_17: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAX5N9B80T01Q_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAX5N9B80T01Q_19: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAX5N9B80T01Q_1A: dc.b $4
	dc.b $E8, $2, $0, $0, $C
	dc.b $F0, $6, $0, $3, $FC
	dc.b $F8, $6, $0, $9, $EC
	dc.b $8, $1, $0, $F, $FC
DATAX5N9B80T01Q_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAX5N9B80T01Q_1C: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAX5N9B80T01Q_1D: dc.b $4
	dc.b $EC, $2, $0, $0, $C
	dc.b $F4, $6, $0, $3, $FC
	dc.b $FC, $6, $0, $9, $EC
	dc.b $C, $0, $0, $F, $FC
DATAX5N9B80T01Q_1E: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
DATAX5N9B80T01Q_1F: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
DATAX5N9B80T01Q_20: dc.b $4
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAX5N9B80T01Q_21: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
DATAX5N9B80T01Q_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATAX5N9B80T01Q_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAX5N9B80T01Q_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATAX5N9B80T01Q_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAX5N9B80T01Q_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAX5N9B80T01Q_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATAX5N9B80T01Q_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAX5N9B80T01Q_29: dc.b $4
	dc.b $F4, $E, $0, $0, $EC
	dc.b $C, $0, $0, $C, $F4
	dc.b $EC, $4, $0, $D, $4
	dc.b $F4, $1, $0, $F, $C
DATAX5N9B80T01Q_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATAX5N9B80T01Q_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAX5N9B80T01Q_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATAX5N9B80T01Q_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAX5N9B80T01Q_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_33: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_35: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAX5N9B80T01Q_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAX5N9B80T01Q_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAX5N9B80T01Q_39: dc.b $2
	dc.b $0, $A, $0, $0, $F3
	dc.b $8, $0, $0, $9, $B
DATAX5N9B80T01Q_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATAX5N9B80T01Q_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATAX5N9B80T01Q_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATAX5N9B80T01Q_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATAX5N9B80T01Q_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAX5N9B80T01Q_3F: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAX5N9B80T01Q_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATAX5N9B80T01Q_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAX5N9B80T01Q_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAX5N9B80T01Q_45: dc.b $2
	dc.b $8, $D, $0, $0, $EC
	dc.b $F0, $A, $0, $8, $F4
DATAX5N9B80T01Q_46: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAX5N9B80T01Q_47: dc.b $2
	dc.b $4, $D, $0, $0, $EC
	dc.b $EC, $A, $0, $8, $F4
DATAX5N9B80T01Q_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAX5N9B80T01Q_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAX5N9B80T01Q_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAX5N9B80T01Q_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAX5N9B80T01Q_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAX5N9B80T01Q_53: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAX5N9B80T01Q_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAX5N9B80T01Q_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAX5N9B80T01Q_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAX5N9B80T01Q_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAX5N9B80T01Q_58: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAX5N9B80T01Q_59: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAX5N9B80T01Q_5A: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAX5N9B80T01Q_5B: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAX5N9B80T01Q_5C: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAX5N9B80T01Q_5D: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
	even