; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Oct 21 2020 22:59:53 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAM8DFLQ09YG:
	dc.w $0, DATAM8DFLQ09YG_1-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_2-DATAM8DFLQ09YG, DATAM8DFLQ09YG_3-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_4-DATAM8DFLQ09YG, DATAM8DFLQ09YG_5-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_6-DATAM8DFLQ09YG, DATAM8DFLQ09YG_7-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_8-DATAM8DFLQ09YG, DATAM8DFLQ09YG_9-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_A-DATAM8DFLQ09YG, DATAM8DFLQ09YG_B-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_C-DATAM8DFLQ09YG, DATAM8DFLQ09YG_D-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_E-DATAM8DFLQ09YG, DATAM8DFLQ09YG_F-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_10-DATAM8DFLQ09YG, DATAM8DFLQ09YG_11-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_12-DATAM8DFLQ09YG, DATAM8DFLQ09YG_13-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_14-DATAM8DFLQ09YG, DATAM8DFLQ09YG_15-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_16-DATAM8DFLQ09YG, DATAM8DFLQ09YG_17-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_18-DATAM8DFLQ09YG, DATAM8DFLQ09YG_19-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_1A-DATAM8DFLQ09YG, DATAM8DFLQ09YG_1B-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_1C-DATAM8DFLQ09YG, DATAM8DFLQ09YG_1D-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_1E-DATAM8DFLQ09YG, DATAM8DFLQ09YG_1F-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_20-DATAM8DFLQ09YG, DATAM8DFLQ09YG_21-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_22-DATAM8DFLQ09YG, DATAM8DFLQ09YG_23-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_24-DATAM8DFLQ09YG, DATAM8DFLQ09YG_25-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_26-DATAM8DFLQ09YG, DATAM8DFLQ09YG_27-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_28-DATAM8DFLQ09YG, DATAM8DFLQ09YG_29-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_2A-DATAM8DFLQ09YG, DATAM8DFLQ09YG_2B-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_2C-DATAM8DFLQ09YG, DATAM8DFLQ09YG_2D-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_2E-DATAM8DFLQ09YG, DATAM8DFLQ09YG_2F-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_30-DATAM8DFLQ09YG, DATAM8DFLQ09YG_31-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_32-DATAM8DFLQ09YG, DATAM8DFLQ09YG_33-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_34-DATAM8DFLQ09YG, DATAM8DFLQ09YG_35-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_36-DATAM8DFLQ09YG, DATAM8DFLQ09YG_37-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_38-DATAM8DFLQ09YG, DATAM8DFLQ09YG_39-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_3A-DATAM8DFLQ09YG, DATAM8DFLQ09YG_3B-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_3C-DATAM8DFLQ09YG, DATAM8DFLQ09YG_3D-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_3E-DATAM8DFLQ09YG, $0
	dc.w DATAM8DFLQ09YG_40-DATAM8DFLQ09YG, DATAM8DFLQ09YG_41-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_42-DATAM8DFLQ09YG, $0
	dc.w $0, DATAM8DFLQ09YG_45-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_46-DATAM8DFLQ09YG, DATAM8DFLQ09YG_47-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_48-DATAM8DFLQ09YG, DATAM8DFLQ09YG_49-DATAM8DFLQ09YG
	dc.w $0, DATAM8DFLQ09YG_4B-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_4C-DATAM8DFLQ09YG, DATAM8DFLQ09YG_4D-DATAM8DFLQ09YG
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w DATAM8DFLQ09YG_54-DATAM8DFLQ09YG, DATAM8DFLQ09YG_55-DATAM8DFLQ09YG
	dc.w DATAM8DFLQ09YG_56-DATAM8DFLQ09YG, DATAM8DFLQ09YG_57-DATAM8DFLQ09YG
DATAM8DFLQ09YG_1: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $C, $C, $0, $D, $EC
	dc.b $C, $0, $0, $11, $C
DATAM8DFLQ09YG_2: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $C, $C, $0, $D, $EC
	dc.b $C, $0, $0, $11, $C
DATAM8DFLQ09YG_3: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $C, $C, $0, $D, $EC
	dc.b $C, $0, $0, $11, $C
DATAM8DFLQ09YG_4: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $C, $C, $0, $D, $EC
	dc.b $C, $0, $0, $11, $C
DATAM8DFLQ09YG_5: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $C, $C, $0, $D, $EC
	dc.b $C, $0, $0, $11, $C
DATAM8DFLQ09YG_6: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $E8
	dc.b $4, $1, $0, $D, $E8
	dc.b $4, $4, $0, $F, $8
	dc.b $C, $0, $0, $11, $8
DATAM8DFLQ09YG_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAM8DFLQ09YG_8: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
	dc.b $F0, $0, $0, $11, $8
DATAM8DFLQ09YG_9: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $E8
	dc.b $4, $1, $0, $D, $E8
	dc.b $4, $4, $0, $F, $8
	dc.b $C, $0, $0, $11, $8
DATAM8DFLQ09YG_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAM8DFLQ09YG_B: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
	dc.b $F0, $0, $0, $11, $8
DATAM8DFLQ09YG_C: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAM8DFLQ09YG_D: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAM8DFLQ09YG_E: dc.b $5
	dc.b $FC, $C, $0, $0, $E8
	dc.b $EC, $9, $0, $4, $F0
	dc.b $4, $8, $0, $A, $F8
	dc.b $C, $8, $0, $D, $0
	dc.b $FC, $0, $0, $10, $8
DATAM8DFLQ09YG_F: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAM8DFLQ09YG_10: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAM8DFLQ09YG_11: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $8, $0, $9, $F4
	dc.b $C, $8, $0, $C, $FC
	dc.b $FC, $0, $0, $F, $4
DATAM8DFLQ09YG_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAM8DFLQ09YG_13: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAM8DFLQ09YG_14: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAM8DFLQ09YG_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAM8DFLQ09YG_16: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAM8DFLQ09YG_17: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAM8DFLQ09YG_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAM8DFLQ09YG_19: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAM8DFLQ09YG_1A: dc.b $4
	dc.b $E8, $2, $0, $0, $C
	dc.b $F0, $6, $0, $3, $FC
	dc.b $F8, $6, $0, $9, $EC
	dc.b $8, $1, $0, $F, $FC
DATAM8DFLQ09YG_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAM8DFLQ09YG_1C: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAM8DFLQ09YG_1D: dc.b $4
	dc.b $EC, $2, $0, $0, $C
	dc.b $F4, $6, $0, $3, $FC
	dc.b $FC, $6, $0, $9, $EC
	dc.b $C, $0, $0, $F, $FC
DATAM8DFLQ09YG_1E: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
DATAM8DFLQ09YG_1F: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
DATAM8DFLQ09YG_20: dc.b $4
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAM8DFLQ09YG_21: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $8, $0, $C, $F0
	dc.b $F4, $2, $0, $F, $8
DATAM8DFLQ09YG_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATAM8DFLQ09YG_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAM8DFLQ09YG_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATAM8DFLQ09YG_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAM8DFLQ09YG_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAM8DFLQ09YG_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATAM8DFLQ09YG_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAM8DFLQ09YG_29: dc.b $4
	dc.b $F4, $E, $0, $0, $EC
	dc.b $C, $0, $0, $C, $F4
	dc.b $EC, $4, $0, $D, $4
	dc.b $F4, $1, $0, $F, $C
DATAM8DFLQ09YG_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATAM8DFLQ09YG_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAM8DFLQ09YG_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATAM8DFLQ09YG_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAM8DFLQ09YG_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_32: dc.b $2
	dc.b $F4, $A, $0, $0, $F3
	dc.b $FC, $0, $0, $9, $B
DATAM8DFLQ09YG_33: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_35: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAM8DFLQ09YG_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAM8DFLQ09YG_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAM8DFLQ09YG_39: dc.b $2
	dc.b $4, $A, $0, $0, $F3
	dc.b $C, $0, $0, $9, $B
DATAM8DFLQ09YG_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATAM8DFLQ09YG_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATAM8DFLQ09YG_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATAM8DFLQ09YG_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATAM8DFLQ09YG_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAM8DFLQ09YG_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATAM8DFLQ09YG_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAM8DFLQ09YG_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAM8DFLQ09YG_45: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $E8
	dc.b $4, $1, $0, $D, $E8
	dc.b $4, $4, $0, $F, $8
	dc.b $C, $0, $0, $11, $8
DATAM8DFLQ09YG_46: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
	dc.b $F0, $0, $0, $11, $8
DATAM8DFLQ09YG_47: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $0, $0, $C, $E8
	dc.b $4, $1, $0, $D, $E8
	dc.b $4, $4, $0, $F, $8
	dc.b $C, $0, $0, $11, $8
DATAM8DFLQ09YG_48: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F0
	dc.b $8, $0, $0, $10, $0
	dc.b $F0, $0, $0, $11, $8
DATAM8DFLQ09YG_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAM8DFLQ09YG_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAM8DFLQ09YG_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAM8DFLQ09YG_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAM8DFLQ09YG_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAM8DFLQ09YG_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAM8DFLQ09YG_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAM8DFLQ09YG_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
	even