; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Oct 22 2020 09:35:56 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAA4F6KWG16BG:
	dc.w $0, DATAA4F6KWG16BG_1-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_2-DATAA4F6KWG16BG, DATAA4F6KWG16BG_3-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_4-DATAA4F6KWG16BG, DATAA4F6KWG16BG_5-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_6-DATAA4F6KWG16BG, DATAA4F6KWG16BG_7-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_8-DATAA4F6KWG16BG, DATAA4F6KWG16BG_9-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_A-DATAA4F6KWG16BG, DATAA4F6KWG16BG_B-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_C-DATAA4F6KWG16BG, DATAA4F6KWG16BG_D-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_E-DATAA4F6KWG16BG, DATAA4F6KWG16BG_F-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_10-DATAA4F6KWG16BG, DATAA4F6KWG16BG_11-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_12-DATAA4F6KWG16BG, DATAA4F6KWG16BG_13-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_14-DATAA4F6KWG16BG, DATAA4F6KWG16BG_15-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_16-DATAA4F6KWG16BG, DATAA4F6KWG16BG_17-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_18-DATAA4F6KWG16BG, DATAA4F6KWG16BG_19-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_1A-DATAA4F6KWG16BG, DATAA4F6KWG16BG_1B-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_1C-DATAA4F6KWG16BG, DATAA4F6KWG16BG_1D-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_1E-DATAA4F6KWG16BG, DATAA4F6KWG16BG_1F-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_20-DATAA4F6KWG16BG, DATAA4F6KWG16BG_21-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_22-DATAA4F6KWG16BG, DATAA4F6KWG16BG_23-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_24-DATAA4F6KWG16BG, DATAA4F6KWG16BG_25-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_26-DATAA4F6KWG16BG, DATAA4F6KWG16BG_27-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_28-DATAA4F6KWG16BG, DATAA4F6KWG16BG_29-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_2A-DATAA4F6KWG16BG, DATAA4F6KWG16BG_2B-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_2C-DATAA4F6KWG16BG, DATAA4F6KWG16BG_2D-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_2E-DATAA4F6KWG16BG, DATAA4F6KWG16BG_2F-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_30-DATAA4F6KWG16BG, DATAA4F6KWG16BG_31-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_32-DATAA4F6KWG16BG, $0
	dc.w $0, $0
	dc.w $0, DATAA4F6KWG16BG_37-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_38-DATAA4F6KWG16BG, DATAA4F6KWG16BG_39-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_3A-DATAA4F6KWG16BG, DATAA4F6KWG16BG_3B-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_3C-DATAA4F6KWG16BG, DATAA4F6KWG16BG_3D-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_3E-DATAA4F6KWG16BG, DATAA4F6KWG16BG_3F-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_40-DATAA4F6KWG16BG, DATAA4F6KWG16BG_41-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_42-DATAA4F6KWG16BG, $0
	dc.w $0, DATAA4F6KWG16BG_45-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_46-DATAA4F6KWG16BG, DATAA4F6KWG16BG_47-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_48-DATAA4F6KWG16BG, DATAA4F6KWG16BG_49-DATAA4F6KWG16BG
	dc.w $0, DATAA4F6KWG16BG_4B-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_4C-DATAA4F6KWG16BG, DATAA4F6KWG16BG_4D-DATAA4F6KWG16BG
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, DATAA4F6KWG16BG_53-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_54-DATAA4F6KWG16BG, DATAA4F6KWG16BG_55-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_56-DATAA4F6KWG16BG, DATAA4F6KWG16BG_57-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_58-DATAA4F6KWG16BG, DATAA4F6KWG16BG_59-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_5A-DATAA4F6KWG16BG, DATAA4F6KWG16BG_5B-DATAA4F6KWG16BG
	dc.w DATAA4F6KWG16BG_5C-DATAA4F6KWG16BG, DATAA4F6KWG16BG_5D-DATAA4F6KWG16BG
DATAA4F6KWG16BG_1: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAA4F6KWG16BG_2: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAA4F6KWG16BG_3: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAA4F6KWG16BG_4: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAA4F6KWG16BG_5: dc.b $4
	dc.b $ED, $B, $0, $0, $F4
	dc.b $F5, $0, $0, $C, $EC
	dc.b $D, $C, $0, $D, $EC
	dc.b $D, $0, $0, $11, $C
DATAA4F6KWG16BG_6: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAA4F6KWG16BG_7: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAA4F6KWG16BG_8: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAA4F6KWG16BG_9: dc.b $5
	dc.b $ED, $B, $0, $0, $F5
	dc.b $F5, $0, $0, $C, $ED
	dc.b $5, $1, $0, $D, $ED
	dc.b $5, $4, $0, $F, $D
	dc.b $D, $0, $0, $11, $D
DATAA4F6KWG16BG_A: dc.b $4
	dc.b $F0, $B, $0, $0, $F3
	dc.b $10, $C, $0, $C, $F3
	dc.b $E8, $4, $0, $10, $FB
	dc.b $F8, $0, $0, $12, $B
DATAA4F6KWG16BG_B: dc.b $4
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $5, $0, $C, $F3
	dc.b $E, $0, $0, $10, $3
	dc.b $F6, $0, $0, $11, $B
DATAA4F6KWG16BG_C: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAA4F6KWG16BG_D: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAA4F6KWG16BG_E: dc.b $5
	dc.b $FC, $C, $0, $0, $E8
	dc.b $EC, $9, $0, $4, $F0
	dc.b $4, $8, $0, $A, $F8
	dc.b $C, $8, $0, $D, $0
	dc.b $FC, $0, $0, $10, $8
DATAA4F6KWG16BG_F: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $0, $6, $0, $9, $F0
	dc.b $F8, $8, $0, $F, $0
	dc.b $F0, $4, $0, $12, $8
DATAA4F6KWG16BG_10: dc.b $5
	dc.b $E8, $A, $0, $0, $F0
	dc.b $F0, $0, $0, $9, $E8
	dc.b $F8, $5, $0, $A, $8
	dc.b $0, $5, $0, $E, $F8
	dc.b $10, $0, $0, $12, $0
DATAA4F6KWG16BG_11: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $8, $0, $9, $F4
	dc.b $C, $8, $0, $C, $FC
	dc.b $FC, $0, $0, $F, $4
DATAA4F6KWG16BG_12: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAA4F6KWG16BG_13: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAA4F6KWG16BG_14: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAA4F6KWG16BG_15: dc.b $5
	dc.b $F8, $E, $0, $0, $EC
	dc.b $10, $0, $0, $C, $F4
	dc.b $E8, $1, $0, $D, $4
	dc.b $10, $4, $0, $F, $4
	dc.b $F0, $0, $0, $11, $C
DATAA4F6KWG16BG_16: dc.b $5
	dc.b $F0, $3, $0, $0, $F8
	dc.b $F0, $3, $0, $4, $10
	dc.b $F8, $5, $0, $8, $E8
	dc.b $F8, $6, $0, $C, $0
	dc.b $8, $0, $0, $12, $F0
DATAA4F6KWG16BG_17: dc.b $4
	dc.b $F0, $E, $0, $0, $E8
	dc.b $8, $0, $0, $C, $F0
	dc.b $F0, $2, $0, $D, $8
	dc.b $F8, $1, $0, $10, $10
DATAA4F6KWG16BG_18: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAA4F6KWG16BG_19: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAA4F6KWG16BG_1A: dc.b $4
	dc.b $E8, $2, $0, $0, $C
	dc.b $F0, $6, $0, $3, $FC
	dc.b $F8, $6, $0, $9, $EC
	dc.b $8, $1, $0, $F, $FC
DATAA4F6KWG16BG_1B: dc.b $4
	dc.b $0, $A, $0, $0, $E8
	dc.b $E8, $5, $0, $9, $F0
	dc.b $F8, $0, $0, $D, $F8
	dc.b $0, $9, $0, $E, $0
DATAA4F6KWG16BG_1C: dc.b $5
	dc.b $F8, $A, $0, $0, $E8
	dc.b $10, $0, $0, $9, $F0
	dc.b $E8, $5, $0, $A, $F8
	dc.b $F8, $5, $0, $E, $0
	dc.b $F8, $0, $0, $12, $10
DATAA4F6KWG16BG_1D: dc.b $4
	dc.b $EC, $2, $0, $0, $C
	dc.b $F4, $6, $0, $3, $FC
	dc.b $FC, $6, $0, $9, $EC
	dc.b $C, $0, $0, $F, $FC
DATAA4F6KWG16BG_1E: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAA4F6KWG16BG_1F: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAA4F6KWG16BG_20: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $8, $0, $C, $F3
	dc.b $F6, $2, $0, $F, $B
DATAA4F6KWG16BG_21: dc.b $2
	dc.b $EE, $F, $0, $0, $F1
	dc.b $E, $8, $0, $10, $F9
DATAA4F6KWG16BG_22: dc.b $4
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $5, $0, $F, $4
DATAA4F6KWG16BG_23: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAA4F6KWG16BG_24: dc.b $5
	dc.b $EC, $A, $0, $0, $EC
	dc.b $4, $C, $0, $9, $F4
	dc.b $C, $4, $0, $D, $FC
	dc.b $F4, $4, $0, $F, $4
	dc.b $FC, $0, $0, $11, $4
DATAA4F6KWG16BG_25: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $4, $8, $0, $C, $FC
	dc.b $C, $0, $0, $F, $FC
	dc.b $F4, $1, $0, $10, $C
DATAA4F6KWG16BG_26: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAA4F6KWG16BG_27: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $0, $0, $C, $F4
	dc.b $F0, $4, $0, $D, $4
	dc.b $F8, $1, $0, $F, $C
DATAA4F6KWG16BG_28: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $F4
	dc.b $F8, $2, $0, $F, $C
DATAA4F6KWG16BG_29: dc.b $4
	dc.b $F4, $E, $0, $0, $EC
	dc.b $C, $0, $0, $C, $F4
	dc.b $EC, $4, $0, $D, $4
	dc.b $F4, $1, $0, $F, $C
DATAA4F6KWG16BG_2A: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $C
	dc.b $FC, $2, $0, $E, $EC
	dc.b $C, $4, $0, $11, $F4
DATAA4F6KWG16BG_2B: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAA4F6KWG16BG_2C: dc.b $6
	dc.b $FC, $A, $0, $0, $EC
	dc.b $EC, $1, $0, $9, $F4
	dc.b $F4, $8, $0, $B, $FC
	dc.b $EC, $0, $0, $E, $4
	dc.b $FC, $4, $0, $F, $4
	dc.b $4, $0, $0, $11, $4
DATAA4F6KWG16BG_2D: dc.b $4
	dc.b $F4, $B, $0, $0, $EC
	dc.b $EC, $8, $0, $C, $F4
	dc.b $F4, $1, $0, $F, $4
	dc.b $FC, $0, $0, $11, $C
DATAA4F6KWG16BG_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAA4F6KWG16BG_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAA4F6KWG16BG_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAA4F6KWG16BG_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAA4F6KWG16BG_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAA4F6KWG16BG_37: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAA4F6KWG16BG_38: dc.b $4
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $4, $0, $C, $0
	dc.b $FC, $0, $0, $E, $8
DATAA4F6KWG16BG_39: dc.b $2
	dc.b $0, $A, $0, $0, $F3
	dc.b $8, $0, $0, $9, $B
DATAA4F6KWG16BG_3A: dc.b $5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $4, $0, $0, $D, $EC
	dc.b $C, $0, $0, $E, $F4
	dc.b $C, $4, $0, $F, $4
DATAA4F6KWG16BG_3B: dc.b $4
	dc.b $C, $8, $0, $0, $E8
	dc.b $EC, $B, $0, $3, $F0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $5, $0, $10, $8
DATAA4F6KWG16BG_3C: dc.b $2
	dc.b $F4, $A, $0, $0, $F0
	dc.b $FC, $0, $0, $9, $8
DATAA4F6KWG16BG_3D: dc.b $2
	dc.b $F0, $A, $0, $0, $F4
	dc.b $8, $0, $0, $9, $FC
DATAA4F6KWG16BG_3E: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAA4F6KWG16BG_3F: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAA4F6KWG16BG_40: dc.b $4
	dc.b $E8, $7, $0, $0, $0
	dc.b $F0, $3, $0, $8, $F8
	dc.b $F8, $0, $0, $C, $F0
	dc.b $8, $1, $0, $D, $0
DATAA4F6KWG16BG_41: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAA4F6KWG16BG_42: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $FC, $1, $0, $F, $10
DATAA4F6KWG16BG_45: dc.b $2
	dc.b $8, $D, $0, $0, $EC
	dc.b $F0, $A, $0, $8, $F4
DATAA4F6KWG16BG_46: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAA4F6KWG16BG_47: dc.b $2
	dc.b $4, $D, $0, $0, $EC
	dc.b $EC, $A, $0, $8, $F4
DATAA4F6KWG16BG_48: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $5, $0, $9, $F4
DATAA4F6KWG16BG_49: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $C, $0, $C, $F0
	dc.b $E8, $4, $0, $10, $F8
	dc.b $F8, $0, $0, $12, $8
DATAA4F6KWG16BG_4B: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAA4F6KWG16BG_4C: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAA4F6KWG16BG_4D: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $C, $0, $C, $F0
	dc.b $10, $0, $0, $10, $F0
DATAA4F6KWG16BG_53: dc.b $2
	dc.b $F4, $A, $8, $0, $F8
	dc.b $FC, $0, $8, $9, $F0
DATAA4F6KWG16BG_54: dc.b $2
	dc.b $F0, $A, $8, $0, $F4
	dc.b $8, $0, $8, $9, $FC
DATAA4F6KWG16BG_55: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAA4F6KWG16BG_56: dc.b $5
	dc.b $EC, $B, $0, $0, $F0
	dc.b $C, $0, $0, $C, $F0
	dc.b $C, $4, $0, $D, $0
	dc.b $F4, $0, $0, $F, $8
	dc.b $4, $0, $0, $10, $8
DATAA4F6KWG16BG_57: dc.b $5
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $0, $0, $9, $E8
	dc.b $F8, $2, $0, $A, $8
	dc.b $0, $0, $0, $D, $10
	dc.b $8, $4, $0, $E, $F8
DATAA4F6KWG16BG_58: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAA4F6KWG16BG_59: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAA4F6KWG16BG_5A: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAA4F6KWG16BG_5B: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAA4F6KWG16BG_5C: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
DATAA4F6KWG16BG_5D: dc.b $2
	dc.b $F9, $E, $0, $0, $F0
	dc.b $11, $8, $0, $C, $F0
	even